### ISSUE TITLE
too long for Unix domain socket

### ISSUE THREAD

**Issue by aa755** [dooblem/bsync#34]
I get the following error when I do
`./bsync /sdcard/work/zot/ home:/home/abhishek/work/zot`

```
unix_listener: "/data/data/com.termux/files/usr/tmp/tmpu4bc4w1x/bsync_abhishek@mybighostname:myport.0texbz3aTGia5AqP" too long for Unix domain socket
Error: could not open SSH connection.
```

**Comment by dooblem** [comment]
Hello @aa755 
Sorry for the late answer.

There is little I can do in bsync.

To work around that you should change the location of the tmp directory.

The directory is created using the mkdtemp call in bsync. Look here:
https://docs.python.org/3.5/library/tempfile.html#tempfile.mkstemp

Try to set the TMPDIR, TEMP or TMP environment variables.

Otherwise you may also slighly change the bsync code to pass a directory as argument to the mkdtemp function.
